# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbf0edeb386d404745f2eba9f92eaee64779d642beb83c840624bd1862b70883161d4b872187cddcdb90ca440e0f8dc64a1bb44c149acbd12ff896324512e786

test:
  secret_key_base: f0c831b00f9f1995e0a2301471d02b886163f593002a2881c0bba46dab055b637fea7d9757b807cdbdaa1cac171653607a4ff0728f9307c1c1699c833d49ff64

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
